force-app/main/default/objects/Account/fields/Jurisdictions__c.field-meta.xml
<CustomField>
    <fullName>Jurisdictions__c</fullName>
    <label>Jurisdictions</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Component__c/Component__c.object-meta.xml
<CustomObject>
    <pluralLabel>Components</pluralLabel>
    <fullName>Component__c</fullName>
    <description>Component for Product</description>
    <sharingModel>ReadWrite</sharingModel>
    <nameField>
        <type>Text</type>
        <label>Component Name</label>
    </nameField>
    <label>Component</label>
</CustomObject>

force-app/main/default/objects/Component__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <type>Currency</type>
    <scale>2</scale>
    <precision>16</precision>
    <description>Price</description>
    <inlineHelpText>Price</inlineHelpText>
    <required>true</required>
    <label>Price</label>
</CustomField>

force-app/main/default/objects/Jurisdiction__c/Jurisdiction__c.object-meta.xml
<CustomObject>
    <description>added from sfdx plugin</description>
    <label>Jurisdiction</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jurisdictions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/JurisdictionProduct__c/JurisdictionProduct__c.object-meta.xml
<CustomObject>
    <description>added from sfdx plugin</description>
    <label>JurisdictionProduct</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>JurisdictionProducts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/JurisdictionProduct__c/fields/Jurisdiction__c.field-meta.xml
<CustomField>
    <fullName>Jurisdiction__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Jurisdiction</label>
    <referenceTo>Jurisdiction__c</referenceTo>
    <relationshipLabel>Jurisdictions</relationshipLabel>
    <relationshipName>JurisdictionsProducts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <pluralLabel>Products</pluralLabel>
    <fullName>Product__c</fullName>
    <description>Products</description>
    <sharingModel>ReadWrite</sharingModel>
    <nameField>
        <type>Text</type>
        <label>Product Name</label>
    </nameField>
    <label>Product</label>
</CustomObject>

force-app/main/default/classes/ProductLineItemService.cls
public with sharing class ProductLineItemService {
    public static List<Product2> getJurisdictionProductLineItemsByOpportunity(String opportunityId){
        List<Product2> products  = new List<Product2>();
        try {
            String pricebookIdForOpportunity = [SELECT Pricebook2Id FROM Opportunity WHERE Id = :opportunityId].Pricebook2Id;
            List<String> jurisdictionIds = new List<String>();
            String jurisdictionIdsStr = [SELECT Jurisdictions__c FROM Account WHERE Id IN (SELECT AccountId FROM Opportunity WHERE Id = :opportunityId)].Jurisdictions__c;
            if(jurisdictionIdsStr != null && jurisdictionIdsStr != ''){
                jurisdictionIds = jurisdictionIdsStr.split(',');
            } 
            products = [SELECT Id, Name, ProductCode, Description, Family, IsActive FROM Product2 WHERE Id IN (SELECT Product2Id FROM PricebookEntry WHERE Pricebook2Id = :pricebookIdForOpportunity) AND Id IN (SELECT Product__c FROM JurisdictionProduct__c WHERE Jurisdiction__c IN :jurisdictionIds)];
        } catch (Exception e) {
            system.debug(e.getMessage() + ' - ' + e.getStackTraceString());
        }
        return products;
    }

    @AuraEnabled
    public static Component__c[] getComponents(){
        try {
           return [SELECT Name,Price__c FROM Component__c];
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}